version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file pdftotxt.yaml --s3-bucket codepipeline-us-east-1-81eea639b0f9-4adf-b1f3-362149536629 --output-template-file lambdaoutput.yaml

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml
