AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::556174328764:role/CodePipelineLambdaExecRole'
      Environment:
        Variables:
          TARGET_BUCKET: bucket1-556174328764
      Layers:
        - 'arn:aws:lambda:us-east-1:556174328764:layer:pypdf_layer:1'
