AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to deploy a Lambda function and supporting S3 bucket.

Parameters:
  LambdaS3Bucket:
    Type: String
    Description: The S3 bucket containing the Lambda deployment package
  LambdaS3Key:
    Type: String
    Description: The S3 key (path/filename) of the Lambda deployment package in the bucket
  LambdaFunctionName:
    Type: String
    Default: MyLambdaFunction
    Description: Name for the Lambda function

Resources:
  # IAM Role for Lambda Execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${LambdaFunctionName}-ExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess   # Example: access to S3
      Path: "/"

  # Lambda Function
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.12              # Change if using Node.js, Java, etc.
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Timeout: 30
      MemorySize: 128

Outputs:
  LambdaFunctionName:
    Value: !Ref MyLambdaFunction
    Description: Name of the Lambda function
